### PR TITLE
Add CDN Installation Instructions.

### LINKED ISSUE #19: Host it onto a CDN
As mentioned in the end of the readme, it would be great to have this hosted on a CDN. I suggest both CDNJS and JsDeliver:
- https://github.com/cdnjs/cdnjs#adding-a-new-or-updating-an-existing-library
- https://github.com/jsdelivr/jsdelivr#how-to-submit-or-update-projects

Cheers

### PR DESCRIPTION
**Pull request by irazasyed**
The PRs got merged with both the CDNs and the files are live :)

This PR Closes #19.

Also, I was thinking maybe we should update the CDN instructions like this, instead of the current one with version:

> [jsDelivr](http://www.jsdelivr.com/#!layzr.js):
> 
> ``` html
> <script src="//cdn.jsdelivr.net/layzr.js/{version}/layzr.min.js"></script>
> ```
> 
> [cdnjs](https://cdnjs.com/libraries/layzr.js):
> 
> ``` html
> <script src="//cdnjs.cloudflare.com/ajax/libs/layzr.js/{version}/layzr.min.js"></script>
> ```
> 
> Replace `{version}` with the library's version you want to use. Refer [releases](https://github.com/callmecavs/layzr.js/releases) section for all the versions. Ex: `1.2.2`.

So that way, You need not worry about updating the README on every release you do, otherwise you'd have to always update the version number in README.

@callmecavs What you think about this?

### CODE REVIEW

**Comment by callmecavs** [comment]
looks good to me! about to merge it and make some small copy edits.  thanks again for the pull requests, and this, huge help

**Comment by irazasyed** [comment]
Awesome, No problem :)

**Comment by callmecavs** [comment]
went ahead and used your versioning idea, and gave you a shoutout in the release notes for 1.2.3 :smile:

thanks again bud!

**Comment by irazasyed** [comment]
Cool, Looks good now :+1: 

Thanks for the shoutout :smile:

**Pull request merged**
