### PR TITLE
support lazy load images in a container

### PR DESCRIPTION
**Pull request by wong2**
As demonstrated in this fiddle:
http://jsfiddle.net/Lbjdc0f0/

I'll update the document if this code looks good to you

### CODE REVIEW

**Comment by wong2** [comment]
@callmecavs any thoughts on this ?

**Comment by callmecavs** [comment]
@wong2 like it a lot - i think it'll make the library more useful for single page web apps. gonna find some time this week to make a few modifications and merge it in. thanks bud

**Comment by siamkreative** [comment]
:+1:

**Comment by callmecavs** [comment]
aiming to have this done today.

@wong2 any way to make changes to your pull request without forking your fork and pull requesting your pull request? :confused: wanna give you credit for your commits but want to do some style cleanup and such.

**Comment by wong2** [comment]
@callmecavs you can fetch my code to your branch, modify the code, commit, push to master (a mannual merge)

**Comment by callmecavs** [comment]
@wong2 rookie question, thanks bud. gonna take a crack at this today - i appreciate your patience

**Comment by wong2** [comment]
any updates?

**Comment by callmecavs** [comment]
@wong2 just pushed v1.4.0 that includes this in it.

couldn't use your commits because the directory structure changed since you made them, but mentioned you in the commit message and the release notes :smile: thanks again for submitting this!

**Comment by wong2** [comment]
@callmecavs great! :beers:

**Pull request merged**
